"use strict";
let places = ['italy', 'Germany', 'Agra', 'Eifel Tower', 'Times Square'];
console.log(places);
console.log([...places].sort());
console.log(places);
console.log([...places].sort().reverse());
console.log(places);
console.log(places.reverse());
console.log(places.reverse());
console.log(places.sort());
console.log(places.sort().reverse());
