"use strict";
let items = ['Quetta', 'Karachi', 'Lahore'];
let items2 = [];
items2.push('Pakistan');
items2.push('India');
items2.push('Australia');
items2.push('Afghanistan');
items2.push('England');
items2.push('South Africa');
console.log(items2);
